# Generated by Django 4.2.7 on 2023-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='revenu',
            field=models.CharField(max_length=20),
        ),
    ]
