# Generated by Django 4.2.7 on 2023-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_customuser_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consiller_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
