# Generated by Django 4.2.7 on 2023-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_customuser_consiller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profil_img/'),
        ),
    ]
