# Generated by Django 4.2.7 on 2023-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_beneficiaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
