# Generated by Django 4.2.7 on 2023-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_card_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('whatsapp', models.CharField(max_length=40)),
            ],
        ),
    ]
